export const DEFAULT_HAUI_LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEuZo0V6xDaIWCHnIYawR2B46F4u6q
pM0ITabLwiVRmoOnChWTUQTX7WhXDwskuU/KfDpQplllG/p2OS90lj+Nqw==
-----END PUBLIC KEY-----`;
