import { describe, expect, it } from 'vitest';
import { parseLicenseInput, verifyLicenseInput } from '../license-verifier';

const CUSTOMER_MACHINE_CODE = 'HAUI-MACHINE-56_8-_7PJ-TEP1';
const DER_SIGNED_LICENSE_CODE =
  'eyJhbGdvcml0aG0iOiJFQ0RTQV9QMjU2X1NIQTI1NiIsInBheWxvYWQiOnsiYnV5ZXIiOiLnrqHnkIblkZgiLCJlZGl0aW9uIjoicHJvIiwiZmVhdHVyZXMiOlsicHJvIiwiYWkiLCJjYW1lcmFfZ3JpZCIsIndhbGxfcGFuZWwiXSwiaXNzdWVkQXQiOiIyMDI2LTA1LTE0IiwibGljZW5zZUlkIjoiSEFVSS0yMDI2MDUxNC0wMDAzIiwibWFjaGluZUNvZGUiOiJIQVVJLU1BQ0hJTkUtNTZfOC1fN1BKLVRFUDEiLCJwcm9kdWN0IjoiSEFVSSIsInVwZGF0ZXNVbnRpbCI6IjIwMjctMDUtMTMifSwic2lnbmF0dXJlIjoiTUVZQ0lRRFlObDh5Z0dYTFhPR1BBQzhhbmZzb1cwcUxZZ01TMXhWODNMbG5YeXIyR3dJaEFLbEdqSTA0YVdXYzJaWjdNck9kaGIzLW9VaFZmMURwNzRyeWNHQ2gtN2V4In0';

describe('license verifier', () => {
  it('accepts DER ECDSA signatures generated by the private license tool', async () => {
    const license = await verifyLicenseInput(DER_SIGNED_LICENSE_CODE, CUSTOMER_MACHINE_CODE);

    expect(license.payload.licenseId).toBe('HAUI-20260514-0003');
    expect(license.payload.machineCode).toBe(CUSTOMER_MACHINE_CODE);
    expect(license.payload.edition).toBe('pro');
  });

  it('rejects licenses for a different machine code before activation', async () => {
    await expect(verifyLicenseInput(DER_SIGNED_LICENSE_CODE, 'HAUI-MACHINE-OTHER')).rejects.toThrow(
      '授权文件与当前机器码不匹配',
    );
  });

  it('parses compact license codes for support diagnostics', () => {
    const license = parseLicenseInput(DER_SIGNED_LICENSE_CODE);

    expect(license.algorithm).toBe('ECDSA_P256_SHA256');
    expect(license.payload.buyer).toBe('管理员');
  });
});
